---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: '7'
inputs:
  - name: sources
  - name: ci
  - name: dependency-cache
    path: /cache
run:
  path: ci/scripts/build.sh
